### ISSUE TITLE
Leaf Blower bugs

### ISSUE THREAD

**Issue by ShinobiDragoon** [Andrew2448/Andrew2448PowersuitAddons#2]
Only tested in SSP. Forge build 666, MPS build 385 and MPSA build 76 are they only things installed on top of MC 1.5.1.

The Leaf Blower does not function if either the Pickaxe Module or Shovel Module is installed, does not seem to be inhibited by any other Module.

The Leaf Blower will only cause Birch Saplings to drop, regardless of the leaf type that is broken (only tested on vanilla trees).

When breaking multiple Leaf Blocks with the Leaf Blower, nearby Leaf Blocks will occasionally turn invisible, and when a player attempts to pass through them the client will argue with itself whether those blocks still exist or not (player will start to be able to move through, then is pushed back out, no crash). Causing a block update can cause the missing blocks to reappear. I assume this issue is more on the vanilla client, but I'm not certain.

**Comment by Andrew2448** [comment]
Alright I'll see what I can do. Bugs were expected :P

**Comment by ShinobiDragoon** [comment]
Yeah, I knew this was a new module and likely to suffer from a few issues, but hopefully having some specifics helps.

I forgot to check after narrowing down the affecting Modules to Pickaxe and Shovel to see if disabling them with keybinds would make a difference. Removed all modules except the Leaf Blower and Pickaxe, then bound the Pickaxe to a key and disabled it. The Leaf Blower was able to function at this point. Same goes for the Shovel. So the problem isn't that the modules are installed, but maybe that they're also looking at the broken block to see what type it was. Perhaps because the Axe also has a search radius function, it doesn't break the Leaf Blower's functionality?

**Comment by Andrew2448** [comment]
I know what the problem is with the shovels/picks, it's something in MPS. I've already fixed the sapling drop (accidentally called the ID rather than the metadata :P). I still have been unable to replicate the "invisible" leaf blocks, are you capable of making a video?

**Comment by ShinobiDragoon** [comment]
I've got a rather poor quality AVI file (hurray for free screen capture software) but GitHub won't let me upload it, anywhere you want me to send it?

The video's frame rate is a bit low, so you can't see that I'm bouncing off the invisible leaves as I try to fall through them and the game forces me back above them. Didn't attempt a block update to make them reappear, but the easiest way I've found is to dump a bucket of water on top of the tree trunk and hopefully the water flow will be adjacent to the leaves that were affected. I did 2 other AoE leaf breaks before I started the video to make sure I could replicate it, and this isn't limited to 2x2 Jungle trees, I've had it happen with a standard Oak as well.

**Comment by Andrew2448** [comment]
I'm building a new build right now that may fix it, try this when it's ready. http://build.technicpack.net/job/ModularPowersuitsAddons/77/

**Comment by ShinobiDragoon** [comment]
Still occurring with MPS build 386 and MPSA build 77. I'm not entirely sure what might be causing it. I thought maybe it was being caused by player movement at the same moment the blocks should be breaking (most commonly caused by breaking the block immediately under the player) but I couldn't get a consistent occurrence with that.

Render issues like this aren't entirely uncommon and aren't limited to your mod. I played quite a bit of SMP during MC 1.4.7 and the simple act of a 2x2 vanilla jungle tree growing would sometimes cause huge areas close to the tree to stop rendering, although the objects were still actually there. Leaving the map and reentering it caused them to render properly again, of course, and sometimes a block update was enough to make them reappear as well, although not always. I think maybe it's something to do with Minecraft itself.

**Comment by Andrew2448** [comment]
I changed to using MC's official way of destroying blocks (world.setBlockToAir(x, y, z);) because i thought it might have been a block update issue, but after this I don't think it's on my side. Hopefully it will sort itself out in the future. Thank you for reporting bugs like an intelligent human being :P
